[build]
  publish   = "."
  functions = "netlify/functions"

# توجه طلب التحقق إلى الدالة
[[redirects]]
  from   = "/.netlify/functions/verify"
  to     = "/.netlify/functions/verify"
  status = 200

# أي مسار غير موجود يعاد إلى index.html (SPA fallback)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
